import { Inter } from 'next/font/google'
import ClientAppProvider from './client-app-provider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" style={{ height: "100%" }}>
      <body style={{ minHeight: "100%" }}>
        <ClientAppProvider>
          {children}
        </ClientAppProvider>
      </body>
    </html>
  )
}
