import { Inter } from 'next/font/google'
import ClientAppProvider from './client-app-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientAppProvider>
          {children}
        </ClientAppProvider>
      </body>
    </html>
  )
}
